server:
  port: 8083
  servlet:
    context-path: /api/v1

spring:
  application:
    name: project-service
  datasource:
    url: jdbc:mariadb://localhost:3306/oneplan_project
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

# JWT Configuration (shared with Identity Service)
jwt:
  secret: ju2n34asbd912nuos1-2anod
  expiration: 86400000  # 24 hours in milliseconds

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
