package com.twelvenexus.oneplan.notification.enums;

public enum NotificationType {
  TASK_ASSIGNED,
  TASK_COMPLETED,
  TASK_OVERDUE,
  COMMENT_ADDED,
  COMMENT_MENTION,
  PROJECT_INVITATION,
  PROJECT_UPDATE,
  REQUIREMENT_ANALYZED,
  STORYBOARD_SHARED,
  SUBSCRIPTION_EXPIRING,
  PAYMENT_FAILED,
  SYSTEM_ANNOUNCEMENT
}
