server:
  port: 8083
  servlet:
    context-path: /api/v1

spring:
  application:
    name: organization-service
  datasource:
    url: jdbc:mariadb://localhost:3306/oneplan_organization
    username: root
    password: rootpassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

# JWT Configuration (shared with Identity Service)
jwt:
  secret: ju2n34asbd912nuos1-2anod
  expiration: 86400000  # 24 hours in milliseconds

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
