server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Identity Service Routes
        - id: identity-service-auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<segment>.*), /api/v1/auth/${segment}

        # Tenant Service Routes
        - id: tenant-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/tenants/**
          filters:
            - RewritePath=/api/v1/tenants/(?<segment>.*), /api/v1/tenants/${segment}

        # Organization Service Routes
        - id: organization-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/organizations/**, /api/v1/teams/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}

        # Project Service Routes
        - id: project-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/projects/**
          filters:
            - RewritePath=/api/v1/projects/(?<segment>.*), /api/v1/projects/${segment}

        # Task Service Routes
        - id: task-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/tasks/**
          filters:
            - RewritePath=/api/v1/tasks/(?<segment>.*), /api/v1/tasks/${segment}

        # Requirement Service Routes
        - id: requirement-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/requirements/**
          filters:
            - RewritePath=/api/v1/requirements/(?<segment>.*), /api/v1/requirements/${segment}

        # Storyboard Service Routes
        - id: storyboard-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/storyboards/**
          filters:
            - RewritePath=/api/v1/storyboards/(?<segment>.*), /api/v1/storyboards/${segment}

        # Integration Service Routes
        - id: integration-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/integrations/**, /api/v1/webhooks/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}

        # Notification Service Routes
        - id: notification-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/notifications/**, /api/v1/preferences/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}

        # Analytics Service Routes
        - id: analytics-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/metrics/**, /api/v1/events/**, /api/v1/reports/**, /api/v1/dashboards/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}

        # Subscription Service Routes
        - id: subscription-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/plans/**, /api/v1/subscriptions/**, /api/v1/payments/**, /api/v1/payment-methods/**, /api/v1/invoices/**, /api/v1/webhooks/razorpay/**, /api/v1/webhooks/phonepe/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

# JWT Configuration
jwt:
  secret: ju2n34asbd912nuos1-2anod
  expiration: 86400000 # 24 hours

# Logging
logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.twelvenexus.oneplan: DEBUG

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,routes,metrics
  endpoint:
    health:
      show-details: always

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      identity-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
      tenant-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
      # Add similar configuration for other services

# Timeouts
spring.cloud.gateway.httpclient.connect-timeout: 10000
spring.cloud.gateway.httpclient.response-timeout: 30s

# Custom headers
spring.cloud.gateway.filter.request-rate-limiter:
  redis-rate-limiter:
    replenish-rate: 10
    burst-capacity: 20
    requested-tokens: 1

