package com.twelvenexus.oneplan.analytics.enums;

public enum MetricType {
    // Project metrics
    PROJECT_CREATED,
    PROJECT_COMPLETED,
    PROJECT_ARCHIVED,
    PROJECT_HEALTH_SCORE,
    PROJECT_TIMELINE_ACCURACY,

    // Task metrics
    TASK_CREATED,
    TASK_COMPLETED,
    TASK_OVERDUE,
    TASK_BLOCKED,
    TASK_CYCLE_TIME,
    TASK_LEAD_TIME,

    // User metrics
    USER_ACTIVE,
    USER_PRODUCTIVITY_SCORE,
    USER_TASK_COMPLETION_RATE,
    USER_AVERAGE_RESPONSE_TIME,

    // Team metrics
    TEAM_VELOCITY,
    TEAM_BURNDOWN,
    TEAM_EFFICIENCY,
    TEAM_COLLABORATION_SCORE,

    // System metrics
    SYSTEM_RESPONSE_TIME,
    SYSTEM_ERROR_RATE,
    SYSTEM_UPTIME,
    SYSTEM_ACTIVE_USERS,

    // AI metrics
    AI_REQUIREMENT_ANALYSIS_ACCURACY,
    AI_SUGGESTION_ACCEPTANCE_RATE,
    AI_PROCESSING_TIME,

    // Business metrics
    SUBSCRIPTION_REVENUE,
    SUBSCRIPTION_CHURN_RATE,
    SUBSCRIPTION_GROWTH_RATE,
    FEATURE_USAGE_RATE
}
